Web-Backend5/Backend5/Models/Patient.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Backend5.Models
{
    public class Patient
    {
        public Int32 Id { get; set; }
        [Required]
        [MaxLength(200)]
        public String Name { get; set; }
        public String Address { get; set; }
        public DateTime Birthday { get; set; }
        public String Gender { get; set; }
        public ICollection<DoctorPatient> Doctors { get; set; }
        public ICollection<Analysis> Analyses { get; set; }
        public ICollection<Diagnosis>Diagnoses { get; set; }
        public ICollection<Placement> Placements { get; set; }





    }
}

Web-Backend5/Backend5/Controllers/AnalysesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Backend5.Data;
using Backend5.Models;
using Backend5.Models.ViewModels;

namespace Backend5.Controllers
{
    public class AnalysesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public AnalysesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Analyses
        public async Task<IActionResult> Index(Int32? patientId)
        {
            if (patientId == null)
            {
                return this.NotFound();
            }

            var patient = await this._context.Patients
                .SingleOrDefaultAsync(x => x.Id == patientId);

            if (patient == null)
            {
                return this.NotFound();
            }

            this.ViewBag.Patient = patient;
            var analyses = await this._context.Analyses
                .Include(w => w.Patient)
                .Include(i=> i.Lab)
                .Where(x => x.PatientId == patientId)
                .ToListAsync();

            return this.View(analyses);
        }

        // GET: Analyses/Details/5
        public async Task<IActionResult> Details(Int32? analysisId)
        {
            if (analysisId == null)
            {
                return NotFound();
            }

            var analysis = await _context.Analyses
                .Include(a => a.Lab)
                .Include(a => a.Patient)
                .SingleOrDefaultAsync(m => m.PatientId == analysisId);
            if (analysis == null)
            {
                return NotFound();
            }

            return View(analysis);
        }

        // GET: Analyses/Create
        public async Task<IActionResult>Create(Int32? patientId)
        {
            if (patientId == null)
            {
                return this.NotFound();
            }
            var patient = await this._context.Patients
                .SingleOrDefaultAsync(x=>x.Id== patientId);
            if (patient == null)
            {
                return this.NotFound();
            }
            this.ViewBag.Patient = patient;
            ViewData["LabId"] = new SelectList(_context.Labs, "Id", "Name");
            return View();
        }

        // POST: Analyses/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Int32? patientId, AnalysesCreateEditViewModel model)
        {

            if (patientId == null)
            {
                return this.NotFound();
            }
            var patient = await this._context.Patients
                .SingleOrDefaultAsync(x => x.Id == patientId);
            if (patient == null)
            {
                return this.NotFound();
            }


            if (ModelState.IsValid)
            {
                var analysisId = this._context.Analyses.Any() ? this._context.Analyses.Max(x => x.AnalysisId) + 1 : 1;
                var analysis = new Analysis
                {
                    PatientId=patient.Id,
                    AnalysisId = analysisId,
                    LabId = model.LabId,
                    Date = model.Date,
                    Status = model.Status,
                    Type = model.Type
                };
                _context.Add(analysis);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index",new {patientId=patientId});
            }

            this.ViewBag.Patient = patient;
            return View(model);
        }

        // GET: Analyses/Edit/5
        public async Task<IActionResult> Edit(Int32? patientId, Int32? analysisId)
        {
            if (patientId == null|| analysisId==null)
            {
                return NotFound();
            }

            var analysis = await _context.Analyses.SingleOrDefaultAsync(m => m.PatientId == patientId && m.AnalysisId==analysisId);
            if (analysis == null)
            {
                return NotFound();
            }
            ViewData["LabId"] = new SelectList(_context.Labs, "Id", "Name", analysis.LabId);
            this.ViewBag.Analysis = analysis;
            return View(analysis);
        }

        // POST: Analyses/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Int32? patientId, Int32? analysisId, AnalysesCreateEditViewModel model)
        {
            if (patientId == null || analysisId == null)
            {
                return NotFound();
            }

            var analysis = await _context.Analyses.SingleOrDefaultAsync(m => m.PatientId == patientId && m.AnalysisId == analysisId);
            if (analysis == null)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                analysis.Status = model.Status;
                analysis.Type = model.Type;
                analysis.Date = model.Date;
                analysis.LabId = model.LabId;
                await _context.SaveChangesAsync();
                return RedirectToAction("Index", new { patientId = patientId });
            }
            return View(model);
        }

        // GET: Analyses/Delete/5
        public async Task<IActionResult> Delete(Int32? patientId, Int32? analysisId)
        {
            if (patientId == null || analysisId == null)
            {
                return NotFound();
            }

            var analysis = await _context.Analyses
                .Include(x=>x.Patient)
                .Include(x=>x.Lab)
                .SingleOrDefaultAsync(m => m.PatientId == patientId && m.AnalysisId == analysisId);
            if (analysis == null)
            {
                return NotFound();
            }

            return View(analysis);
        }

        // POST: Analyses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Int32? patientId, Int32? analysisId)
        {
            var analysis = await _context.Analyses.SingleOrDefaultAsync(m => m.PatientId == patientId && m.AnalysisId == analysisId);
            _context.Analyses.Remove(analysis);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index", new { patientId = patientId });
        }

        
    }
}

Web-Backend5/Backend5/Controllers/DiagnosesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Backend5.Data;
using Backend5.Models;
using Backend5.Models.ViewModels;

namespace Backend5.Controllers
{
    public class DiagnosesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public DiagnosesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Diagnoses
        public async Task<IActionResult> Index(Int32? patientId)
        {
            if (patientId == null)
            {
                return this.NotFound();
            }
            var patient = await this._context.Patients
                .SingleOrDefaultAsync(x => x.Id == patientId);
            if (patient == null)
            {
                return this.NotFound();
            }

            var items = await this._context.Diagnoses
                .Include(p => p.Patient)
                .Where(x => x.PatientId == patientId)
                .ToListAsync();

            this.ViewBag.Patient = patient;
            return View(items);
        }

        // GET: Diagnoses/Details/5
        public async Task<IActionResult> Details(Int32? patientId, Int32? diagnosisId)
        {
            if (patientId == null || diagnosisId == null)
            {
                return NotFound();
            }

            var diagnosis = await _context.Diagnoses
                .Include(d => d.Patient)
                .SingleOrDefaultAsync(m => m.DiagnosisId == diagnosisId && m.PatientId==patientId );
            if (diagnosis == null)
            {
                return NotFound();
            }

            return View(diagnosis);
        }

        // GET: Diagnoses/Create
        public async Task<IActionResult>Create(Int32? patientId)
        {
            if (patientId == null)
            {
                return this.NotFound();
            }
            var patient = await this._context.Patients
                .SingleOrDefaultAsync(x => x.Id == patientId);
            if (patient == null)
            {
                return this.NotFound();
            }
            this.ViewBag.Patient = patient;

            return View();
        }

        // POST: Diagnoses/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create( Int32? patientId, DiagnosesCreateViewModel model )
        {
            if (patientId == null)
            {
                return this.NotFound();
            }
            var patient = await this._context.Patients
                .SingleOrDefaultAsync(x => x.Id == patientId);
            if (patient == null)
            {
                return this.NotFound();
            }


            if (ModelState.IsValid)
            {
                var diagnosisId = this._context.Diagnoses.Any() ? this._context.Diagnoses.Max(x => x.DiagnosisId) + 1 : 1;
                var diagnosis = new Diagnosis 
                {
                    PatientId=patient.Id,
                    DiagnosisId=diagnosisId,
                    Type=model.Type,
                    Complications=model.Complications,
                    Details=model.Details
                };

                _context.Add(diagnosis);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index", new { patientId = patient.Id });
            }
            this.ViewBag.Patient = patient;
            return this.View(model);
        }

        // GET: Diagnoses/Edit/5
        public async Task<IActionResult> Edit(Int32? patientId,Int32? diagnosisId)
        {
            if (patientId == null|| diagnosisId == null)
            {
                return NotFound();
            }

            var diagnosis = await _context.Diagnoses.SingleOrDefaultAsync(m => m.DiagnosisId == diagnosisId && m.PatientId==patientId);
            if (diagnosis == null)
            {
                return NotFound();
            }
            ViewData["PatientId"] = new SelectList(_context.Patients, "Id", "Name", diagnosis.PatientId);
            return View(diagnosis);
        }

        // POST: Diagnoses/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Int32? patientId, Int32? diagnosisId,  DiagnosesCreateViewModel model)
        {
            if (patientId == null || diagnosisId == null)
            {
                return NotFound();
            }

            var diagnosis = await _context.Diagnoses.SingleOrDefaultAsync(m => m.DiagnosisId == diagnosisId && m.PatientId == patientId);
            if (diagnosis == null)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                diagnosis.Type = model.Type;
                diagnosis.Details = model.Details;
                diagnosis.Complications = model.Complications;
                await _context.SaveChangesAsync();
                return RedirectToAction("Index", new { patientId = patientId });
            }
            
            return View(diagnosis);
        }

        // GET: Diagnoses/Delete/5
        public async Task<IActionResult> Delete(Int32? patientId, Int32? diagnosisId)
        {
            if (patientId == null || diagnosisId == null)
            {
                return NotFound();
            }

            var diagnosis = await _context.Diagnoses.Include(x=>x.Patient).SingleOrDefaultAsync(m => m.DiagnosisId == diagnosisId && m.PatientId == patientId);
            if (diagnosis == null)
            {
                return NotFound();
            }
            

            return View(diagnosis);
        }

        // POST: Diagnoses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Int32? patientId, Int32? diagnosisId)
        {
            var diagnosis = await _context.Diagnoses.SingleOrDefaultAsync(m => m.DiagnosisId == diagnosisId && m.PatientId == patientId);
            _context.Diagnoses.Remove(diagnosis);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index", new { patientId = patientId });
        }

       
    }
}

Web-Backend5/Backend5/Views/Patients/Create.cshtml
@model Backend5.Models.ViewModels.PatientCreateEditViewModel

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>Patient</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Birthday" class="control-label"></label>
                <input asp-for="Birthday" class="form-control" />
                <span asp-validation-for="Birthday" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Gender" class="control-label"></label>
                <input asp-for="Gender" class="form-control" />
                <span asp-validation-for="Gender" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Web-Backend5/Backend5/Views/Patients/Delete.cshtml
@model Backend5.Models.Patient

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Patient</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Birthday)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Birthday)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Gender)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Gender)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Web-Backend5/Backend5/Views/Patients/Details.cshtml
@model Backend5.Models.Patient

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>Patient</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Birthday)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Birthday)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Gender)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Gender)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Index" asp-controller="Diagnoses" asp-route-patientId="@Model.Id">Diagnoses</a> |
    <a asp-action="Index" asp-controller="Analyses" asp-route-patientId="@Model.Id">Analyses</a> |
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Web-Backend5/Backend5/Views/Patients/Edit.cshtml
@model Backend5.Models.ViewModels.PatientCreateEditViewModel

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>Patient</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
             
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Birthday" class="control-label"></label>
                <input asp-for="Birthday" class="form-control" />
                <span asp-validation-for="Birthday" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Gender" class="control-label"></label>
                <input asp-for="Gender" class="form-control" />
                <span asp-validation-for="Gender" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Web-Backend5/Backend5/Views/Patients/Index.cshtml
@model IEnumerable<Backend5.Models.Patient>

@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Address)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Birthday)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Gender)
                </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Address)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Birthday)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Gender)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>