Web-Backend6/Backend6/Models/ForumTopics.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Backend6.Models
{
    public class ForumTopic
    {
        public Guid Id { get; set; } = Guid.NewGuid();
        public Guid ForumId { get; set; }
        public Forum Forum { get; set; }

        [Required]
        public String CreatorId { get; set; }
        public ApplicationUser Creator { get; set; }
        public DateTime Created { get; set; }

        [Required]
        [MaxLength(200)]
        public String Name { get; set; }

        public ICollection<ForumMessage> ForumMessages { get; set; }
    }
}

Web-Backend6/Backend6/Controllers/ForumMessagesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Backend6.Data;
using Backend6.Models;
using Microsoft.AspNetCore.Identity;
using Backend6.Services;
using Backend6.Models.ViewModels;

namespace Backend6.Controllers
{
    public class ForumMessagesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> userManager;
        private readonly IUserPermissionsService userPermissions;
        public ForumMessagesController(ApplicationDbContext context, UserManager<ApplicationUser> userManager, IUserPermissionsService userPermissions)
        {
            this.userManager = userManager;
            this.userPermissions = userPermissions;
            this._context = context;
        }

        // GET: ForumMessages/Create
        public async  Task<IActionResult> Create(Guid id)
        {
            if (id==null)
            {
                return this.NotFound();
            }
            var topic = await this._context.ForumTopics
                .SingleOrDefaultAsync(x => x.Id == id);
            if (topic == null)
            {
                return this.NotFound();
            }
            var model = new ForumMessagesEditViewModel();
            this.ViewBag.Topic = topic;
            return View(model);
        }

        // POST: ForumMessages/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Guid id,ForumMessagesEditViewModel model)
        {
            if (id == null)
            {
                return this.NotFound();
            }
            var topic = await this._context.ForumTopics
                .SingleOrDefaultAsync(x => x.Id == id);
            if (topic == null)
            {
                return this.NotFound();
            }
            if (ModelState.IsValid)
            {
                var user = await this.userManager.GetUserAsync(this.HttpContext.User);
                var now = DateTime.UtcNow;
                var message = new ForumMessage()
                {
                    Text = model.Text,
                    CreatorId = user.Id,
                    TopicId=topic.Id,
                    Created = now,
                    Modified = null
                };

                _context.Add(message);
                await _context.SaveChangesAsync();
                this.ViewBag.Topic = topic;
                return RedirectToAction("Index","ForumTopics",new { id=topic.Id});
            }
            return View(model);
        }

        // GET: ForumMessages/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var forumMessage = await _context.ForumMessages.SingleOrDefaultAsync(m => m.Id == id);
            if (forumMessage == null)
            {
                return NotFound();
            }
            this.ViewBag.Message = forumMessage;
            var model = new ForumMessagesEditViewModel
            {
                Text = forumMessage.Text
            };

            return View(model);
        }

        // POST: ForumMessages/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, ForumMessagesEditViewModel model)
        {
            if (id == null)
            {
                return NotFound();
            }

            var forumMessage = await _context.ForumMessages
                .Include(x=>x.Topic)
                .SingleOrDefaultAsync(m => m.Id == id);
            if (forumMessage == null)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                forumMessage.Text = model.Text;
                forumMessage.Modified = DateTime.UtcNow;
                await _context.SaveChangesAsync();
                return RedirectToAction("Index","ForumTopics",new { id=forumMessage.TopicId});
            }
            return View(forumMessage);
        }

        // GET: ForumMessages/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var forumMessage = await _context.ForumMessages
                .Include(f => f.Creator)
                .Include(f => f.Topic)
                .SingleOrDefaultAsync(m => m.Id == id);
            if (forumMessage == null)
            {
                return NotFound();
            }

            return View(forumMessage);
        }

        // POST: ForumMessages/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var forumMessage = await _context.ForumMessages
                .Include(f => f.Creator)
                .Include(f => f.Topic)
                .SingleOrDefaultAsync(m => m.Id == id);
            if (forumMessage == null)
            {
                return NotFound();
            }
            var topic = forumMessage.Topic;
            _context.ForumMessages.Remove(forumMessage);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index","ForumTopics",topic);
        }

        private bool ForumMessageExists(Guid id)
        {
            return _context.ForumMessages.Any(e => e.Id == id);
        }
    }
}

Web-Backend6/Backend6/Controllers/ForumTopicsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Backend6.Data;
using Backend6.Models;
using Backend6.Services;
using Microsoft.AspNetCore.Identity;
using Backend6.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;

namespace Backend6.Controllers
{
    [Authorize]
    public class ForumTopicsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> userManager;
        private readonly IUserPermissionsService userPermissions;
        public ForumTopicsController(ApplicationDbContext context, UserManager<ApplicationUser> userManager, IUserPermissionsService userPermissions)
        {
            this.userManager = userManager;
            this.userPermissions = userPermissions;
            this._context = context;
        }

        // GET: ForumTopics
        [AllowAnonymous]
        public async Task<IActionResult> Index(Guid id)
        {
            if (id==null)
            {
                this.NotFound();
            }
            var topic = await this._context.ForumTopics
                .Include(x=>x.ForumMessages).ThenInclude(x=>x.Attachments)
                .Include(x=>x.ForumMessages).ThenInclude(x=>x.Creator)
                .Include(x=>x.Forum)
                .Include(x=>x.Creator)
                .SingleOrDefaultAsync(x =>x.Id==id);

            if (topic== null)
            {
                this.NotFound();
            }
            return View(topic);
        }

      

        // GET: ForumTopics/Create
        public async Task<IActionResult>Create(Guid id)
        {
            if (id == null)
            {
                this.NotFound();
            }
            var forum= await this._context.Forums
                .SingleOrDefaultAsync(x => x.Id == id);

            if (forum== null)
            {
                this.NotFound();
            }
            this.ViewBag.Forum = forum;
            return View(new ForumTopicsEditViewModel());
        }

        // POST: ForumTopics/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Guid id,ForumTopicsEditViewModel model)
        {
            if (id == null)
            {
                this.NotFound();
            }
            var forum = await this._context.Forums
                .SingleOrDefaultAsync(x => x.Id == id);

            if (forum == null)
            {
                this.NotFound();
            }
            var user = await this.userManager.GetUserAsync(this.HttpContext.User);
            if (ModelState.IsValid)
            {
                var topic = new ForumTopic
                {
                    ForumId=forum.Id,
                    Created = DateTime.UtcNow,
                    Name=model.Name,
                    CreatorId=user.Id,
                };
                _context.Add(topic);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index","Forum",new { id=id});
            }
            return View(model);
        }

        // GET: ForumTopics/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var forumTopic = await _context.ForumTopics.SingleOrDefaultAsync(m => m.Id == id);
            if (forumTopic == null  )
            {
                return NotFound();
            }
            var model = new ForumTopicsEditViewModel 
            {
                Name=forumTopic.Name
                
            };
            this.ViewBag.Topic = forumTopic;
            return View(model);
        }

        // POST: ForumTopics/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, ForumTopicsEditViewModel model)
        {
            if (id == null)
            {
                return NotFound();
            }

            var forumTopic = await _context.ForumTopics
                .Include(x=>x.Forum)
                .SingleOrDefaultAsync(m => m.Id == id);
            if (forumTopic == null)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                forumTopic.Name = model.Name;
                await _context.SaveChangesAsync();
                return RedirectToAction("Index","Forum",new { id=forumTopic.ForumId});
            }
            return View(forumTopic);
        }

        // GET: ForumTopics/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var forumTopic = await _context.ForumTopics
                .Include(f => f.Creator)
                .Include(f => f.Forum)
                .SingleOrDefaultAsync(m => m.Id == id);
            if (forumTopic == null)
            {
                return NotFound();
            }

            return View(forumTopic);
        }

        // POST: ForumTopics/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var  topic = await _context.ForumTopics
                .Include(f => f.Creator)
                .Include(f => f.Forum)
                .SingleOrDefaultAsync(m => m.Id == id);
            if (topic == null)
            {
                return NotFound();
            }
            var forum = topic.Forum;
            var forumTopic = await _context.ForumTopics.SingleOrDefaultAsync(m => m.Id == id);
            _context.ForumTopics.Remove(forumTopic);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index","Forum",forum);
        }

        private bool ForumTopicExists(Guid id)
        {
            return _context.ForumTopics.Any(e => e.Id == id);
        }
    }
}

Web-Backend6/Backend6/Views/ForumTopics/Create.cshtml
@model Backend6.Models.ViewModels.ForumTopicsEditViewModel

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>ForumTopic</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create"asp-route-id="@ViewBag.Forum.Id">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index"asp-controller="Forum"asp-route-id="ViewBag.Forum.Id">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Web-Backend6/Backend6/Views/ForumTopics/Delete.cshtml
@model Backend6.Models.ForumTopic

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ForumTopic</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Created)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Created)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Creator)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Creator.Id)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Forum)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Forum.Description)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Web-Backend6/Backend6/Views/ForumTopics/Details.cshtml
@model Backend6.Models.ForumTopic

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>ForumTopic</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Created)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Created)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Creator)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Creator.Id)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Forum)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Forum.Description)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Web-Backend6/Backend6/Views/ForumTopics/Edit.cshtml
@model Backend6.Models.ViewModels.ForumTopicsEditViewModel

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>ForumTopic</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" asp-route-id="@ViewBag.Topic.Id">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" asp-route-id="@ViewBag.Topic.Id">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Web-Backend6/Backend6/Views/ForumTopics/Index.cshtml
@using Backend6.Services
@inject IUserPermissionsService UserPermissions
@model Backend6.Models.ForumTopic
@{
    ViewBag.Title = "Topic";
}

<h2>@Model.Name</h2>
@if (User.Identity.IsAuthenticated)
{
    <p>
        <a asp-action="Create" asp-controller="ForumMessages" asp-route-id="@Model.Id">Reply</a>
        @if (UserPermissions.CanEditForumTopic(Model))
        {
            <span>
                | <a asp-action="Edit" asp-controller="ForumTopics" asp-route-id="@Model.Id">Edit</a>
                | <a asp-action="Delete" asp-controller="ForumTopics" asp-route-id="@Model.Id">Delete</a>
            </span>
        }
        | <a asp-action="Index" asp-controller="Forum" asp-route-id="@Model.Forum.Id">Back to @Model.Forum.Name</a>
    </p>
}

@foreach (var item in Model.ForumMessages)
{
    <div class="panel panel-default">
        <div class="panel-heading">
            <div>
                @item.Creator.UserName, @item.Created @if (item.Modified.HasValue)
                {<span>(edited @item.Modified  )</span>}
                @if (UserPermissions.CanEditForumMessage(item))
                {
                    <span>
                        | <a asp-action="Edit" asp-controller="ForumMessages" asp-route-id="@item.Id">Edit</a>
                        | <a asp-action="Delete" asp-controller="ForumMessages" asp-route-id="@item.Id">Delete</a>
                        | <a asp-action="Create" asp-controller="ForumMessageAttachments" asp-route-id="@item.Id">Attach</a>
                    </span>
                }
               
            </div>
        </div>
        <div class="panel-body">
            <div class="forum-message-text">
                @item.Text
            </div>
            @foreach (var pic in item.Attachments)
            {
                <div class="col-sm-6 col-md-4">
                    <div class="thumbnail">
                        <img src="@pic.FilePath" alt="Image" />
                        @if (UserPermissions.CanEditForumMessage(item))
                        {
                    <div class="caption">
                        <p><a asp-action="Delete" asp-controller="ForumMessageAttachments" asp-route-id="@pic.Id" class="btn btn-danger">Delete</a></p>
                    </div>
                        }
                        
                    </div>
                </div>
            }
        </div>
    </div>
}